# copy content to docker-compose.yml file
# run `docker-compose up` to start both containers, ctrl+c to stop them
# run `docker-compose down -v` to remove containers and docker volumes

version: "3.8"

networks:
  elk:
    driver: bridge

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: sl-elastic
    networks:
      - elk
    volumes:
      - sl-elastic:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
    ports:
      - 9200:9200
    expose:
      - 9200
  kibana:
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: sl-kibana
    networks:
      - elk
    volumes:
      - sl-kibana:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
    expose:
      - 5601
#  node:
#    build: .
#    container_name: sl-node
#    volumes:
#      - sl-node:/usr/share/node/data
#    ports:
#      - 3000:3000
volumes:
  sl-elastic:
    driver: local
  sl-kibana:
    driver: local
  sl-node:
    driver: local
